services:
  frontend:
    image: nginx
    container_name: frontend
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      - NGINX_PORT=80
    volumes:
      - "./frontend:/usr/share/nginx/html"
